### PR TITLE
Targetable Imprecise Senses

### PR DESCRIPTION
**Pull request by txm3278**
Makes tokens seen by imprecise senses (like hearing) targetable for closed issue #18 
image

This is toggleable in the settings (defaults to off)
image

### CODE REVIEW

**Comment by dev7355608** [comment]
Thanks for the contribution. But we cannot make an imprecise token visible for targeting, because that may reveal the identity of the token entirely and therefore make imprecise detection functionally equivalent to precise detection. If the token is visible, it may reveal
- the disposition,
- the name,
- the HP,
- the status effects,
- the targets of the GM and other players,
- the elevation, and
- other things that are displayed by other modules such as Health Estimate for example.

In the current state of the PR even the token icon is revealed.

image

We would need to make the imprecise mesh targetable instead to prevent information from being revealed.

**Comment by txm3278** [comment]
Making the imprecise mesh targetable is what I originally tried to do but could not figure out a way to make that happen. It seems like Foundry only attacks on the mesh. You would know a lot better than me about this, so if you have any ideas I would be happy to test them out.

I was sent this line,
image
by Lukas that hid more information about the imprecise token but I didn't include it in this PR in order to not bloat this.

This like makes the token look like this (includes a large and medium creature):
image

**Comment by LukasPrism** [comment]
> Thanks for the contribution. But we cannot make an imprecise token visible for targeting, because that may reveal the identity of the token entirely and therefore make imprecise detection functionally equivalent to precise detection. If the token is visible, it may reveal
> 
> * the disposition,
> * the name,
> * the HP,
> * the status effects,
> * the targets of the GM and other players,
> * the elevation, and
> * other things that are displayed by other modules such as Health Estimate for example.
> 
> In the current state of the PR even the token icon is revealed.
> 
> image
> 
> We would need to make the imprecise mesh targetable instead to prevent information from being revealed.

Hi folks,

We just ran a three hour combat in blinding fog, and just some feedback here that we were super glad we were testing this patched version of V5E. There were a dozen wights in the fog and being able to target them ourselves kept combat flowing nice and smoothly. We never have the ability to see enemy HP bars anyway, and the GM has control over nameplates using Anonymous. We _do_ use Health Estimate, but in this case the GM really didn't mind at all if we had an idea of how wounded the unseen enemies are, it is an estimate anyway.

Because we're using midi – all the advantage/disadvantage attribution was handled perfectly as it should be with unseen attackers, meaning we didn't have to worry about that. Things like Reckless Attack and Steady Aim still allowed us to attack the unseen foes without disadvantage as they should – all calculated automatically.

The other revealed info you mention I wouldn't consider too much of a concern if it was a trade-off to make this targeting happen – being able to see AEs means the ranger could keep track of hunter's mark and favoured foe (that's pretty cool anyway). Elevation is fine.

Having said that, if there was an option for targetable imprecise meshes that _also_ hid the other info you listed – that would be phenomenal.

Many thanks!

**Comment by txm3278** [comment]
With the latest update to the hearing animation, it now looks like this,
image

I looked further into the making the impreciseMesh targetable, it seems this is possible by setting token.visible to true and token.mesh.visible to false. This unfortunately seems impossible right now in foundry because setting one, sets the other.

**Comment by txm3278** [comment]
While making it work with the existing impreciseMesh was not possible through my testing (hopefully fixed in v12), I did go through and hide all UI elements from imprecise tokens that could give away info about them. If there is any changes you want, I would be happy to make them.

https://github.com/dev7355608/vision-5e/assets/25332081/c0f8a392-330b-417a-84dc-621d6270cb36

**Comment by LukasPrism** [comment]
Love the huge recent update @dev7355608 !

And this is amazing, thanks @txm3278. Looking forward to testing it out!

Personally I don’t see why revealing elevation is an issue. You know the enemy is exactly ten feet north and fifteen feet west of you, but not ten feet above you? I’m not bothered if it needs to stay hidden as a compromise but conceptually I think it would ideally still be showing. 

Thanks both 😀

**Comment by Zamrod** [comment]
I would also like to see this merged. Being unable to target these tokens has been rather frustrating.

**Comment by samgrieve** [comment]
+1 to this!

**Comment by gambit07** [comment]
Would like to see it merged as well!

**Comment by dineshm72** [comment]
I understand the desire to reduce information leakage, but IMO reducing the practical effects of combat friction is a larger concern which should take priority.  Suggesting that all targeting of imprecise targets need be done via the GM seems heavy handed, particularly when doing so will leak some of the same information that allowing players to do it themselves would also leak.

Furthermore, I think that some of the potential info leakages identified already exist from many other sources, especially the combat tracker and many modules which enhance it with additional information.  Furthermore, targeting may already carry over for some player tokens from previous rounds depending on game setup, which can add additional experiential variance.

If the goal of reducing information leakage is desired, which I otherwise fully support, I suspect the way to handle it is with other fixes in core, not by restricting what is allowable when using this module.  Have core develop a "targetable" flag for each token which controls whether a token can be targetable or identifiable (from any source).  Develop mechanisms to hide information about selected tokens from the combat tracker and prevent it from being used to target, or being used to identify tokens on the canvas, or to otherwise leak information about status effects.  Etc.

Anyway, my opinion only.  Thanks for listening!

**Comment by txm3278** [comment]
Thank you for the new patch! Your solution is something I was investigation but couldn't get working. Thanks for taking a look into this.

**Pull request closed without merging**
