### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by Yx2xY**
Hello there, 

First time committing a pull request, so hopefully everything is in order.

I've done the Spanish translation and localization. I used the names found in the official ESP books that I have available. I tried to use the exact terminology so automatic matching should work (I tested with umbral sight and it's working).

There is one case where I did not change the name of the feature ("Hollow One" in "/detection modes/divine-sense.js") as it's from a book who does not have an official ESP localization and I did not dare to use non official terminology.

Thanks for this module and for all your work.

### CODE REVIEW

**Comment by dev7355608** [comment]
Thank you for your contribution!

Among other smaller fixes, I made some changes to capitalization: some translations only capitalized the first letter, others nouns, verbs, and adjectives too. Now only the first letter is capitalized, but I'm not sure if this the proper capitalization. Feel free to correct this. Perhaps it was correct already, and I just messed it up.

I added "Aquel que está vacío" for the translation of "Hollow One", which is from the official translation of the MTG card "Hollow One". Let me know if that makes sense.

**Comment by Yx2xY** [comment]
Hi, always happy to help! 

In relation to the capitalization issue, that is a confusing one. In Spanish we don't usually capitalize every first letter of a word, only those that initiates the sentence as in your fix. 

In the localized books those are all over the place they capitalize the first letter of a complete word of some features, spells or titles, but in other places it follows the correct grammar rules for Spanish, but your normalization is the correct way to write in Spanish in general. I just followed the book's styling to avoid any issues. 

"Hollow One" as "Aquel que está vacío" it's a perfect fit. I completely forgot that Theros was a plane from MGT

**Comment by dev7355608** [comment]
Okay, thanks! Let's keep the capitalization then that only capitalized the first letter of the first word. This only affects the translations of the modes in the detection modes tab of the token config anyway. The automated detection of features/spell effects is not case-sensitive. So anyone that wants to can us different capitalization for the feature/spell names.

**Comment by dev7355608** [comment]
https://github.com/dev7355608/vision-5e/releases/tag/v1.12.0

**Pull request merged**
